// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxZ2kBMJGbK1JxIETwFOStPdR0C4D7Bds',
    appId: '1:277360264120:web:e756cde322e3fb1edc054d',
    messagingSenderId: '277360264120',
    projectId: 'basarsapp',
    authDomain: 'basarsapp.firebaseapp.com',
    storageBucket: 'basarsapp.firebasestorage.app',
    measurementId: 'G-VQBG742C61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCHDAaFR0e7r3EBa2Ppni7NaXcfozpIaA',
    appId: '1:277360264120:android:c88eb765ad60af64dc054d',
    messagingSenderId: '277360264120',
    projectId: 'basarsapp',
    storageBucket: 'basarsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfH3BDXwRcVBrIXs2HvIrxp99tnVCK-KQ',
    appId: '1:277360264120:ios:dd86c691807d3d04dc054d',
    messagingSenderId: '277360264120',
    projectId: 'basarsapp',
    storageBucket: 'basarsapp.firebasestorage.app',
    iosBundleId: 'com.example.basarsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfH3BDXwRcVBrIXs2HvIrxp99tnVCK-KQ',
    appId: '1:277360264120:ios:dd86c691807d3d04dc054d',
    messagingSenderId: '277360264120',
    projectId: 'basarsapp',
    storageBucket: 'basarsapp.firebasestorage.app',
    iosBundleId: 'com.example.basarsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxZ2kBMJGbK1JxIETwFOStPdR0C4D7Bds',
    appId: '1:277360264120:web:5469256ec5b64f04dc054d',
    messagingSenderId: '277360264120',
    projectId: 'basarsapp',
    authDomain: 'basarsapp.firebaseapp.com',
    storageBucket: 'basarsapp.firebasestorage.app',
    measurementId: 'G-JVTP9WHTXL',
  );
}
